// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package recoder_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RecoderClient is the client API for Recoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoderClient interface {
	SetLoggingLevel(ctx context.Context, in *SetLoggingLevelRequest, opts ...grpc.CallOption) (*SetLoggingLevelReply, error)
	NewContext(ctx context.Context, in *NewContextRequest, opts ...grpc.CallOption) (*NewContextReply, error)
	NewInput(ctx context.Context, in *NewInputRequest, opts ...grpc.CallOption) (*NewInputReply, error)
	NewOutput(ctx context.Context, in *NewOutputRequest, opts ...grpc.CallOption) (*NewOutputReply, error)
	CloseContext(ctx context.Context, in *CloseContextRequest, opts ...grpc.CallOption) (*CloseContextReply, error)
	CloseInput(ctx context.Context, in *CloseInputRequest, opts ...grpc.CallOption) (*CloseInputReply, error)
	CloseOutput(ctx context.Context, in *CloseOutputRequest, opts ...grpc.CallOption) (*CloseOutputReply, error)
	StartRecoding(ctx context.Context, in *StartRecodingRequest, opts ...grpc.CallOption) (*StartRecodingReply, error)
	GetStats(ctx context.Context, in *GetRecoderStatsRequest, opts ...grpc.CallOption) (*GetRecoderStatsReply, error)
	RecodingEndedChan(ctx context.Context, in *RecodingEndedChanRequest, opts ...grpc.CallOption) (Recoder_RecodingEndedChanClient, error)
}

type recoderClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoderClient(cc grpc.ClientConnInterface) RecoderClient {
	return &recoderClient{cc}
}

func (c *recoderClient) SetLoggingLevel(ctx context.Context, in *SetLoggingLevelRequest, opts ...grpc.CallOption) (*SetLoggingLevelReply, error) {
	out := new(SetLoggingLevelReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/SetLoggingLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) NewContext(ctx context.Context, in *NewContextRequest, opts ...grpc.CallOption) (*NewContextReply, error) {
	out := new(NewContextReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/NewContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) NewInput(ctx context.Context, in *NewInputRequest, opts ...grpc.CallOption) (*NewInputReply, error) {
	out := new(NewInputReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/NewInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) NewOutput(ctx context.Context, in *NewOutputRequest, opts ...grpc.CallOption) (*NewOutputReply, error) {
	out := new(NewOutputReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/NewOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) CloseContext(ctx context.Context, in *CloseContextRequest, opts ...grpc.CallOption) (*CloseContextReply, error) {
	out := new(CloseContextReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/CloseContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) CloseInput(ctx context.Context, in *CloseInputRequest, opts ...grpc.CallOption) (*CloseInputReply, error) {
	out := new(CloseInputReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/CloseInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) CloseOutput(ctx context.Context, in *CloseOutputRequest, opts ...grpc.CallOption) (*CloseOutputReply, error) {
	out := new(CloseOutputReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/CloseOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) StartRecoding(ctx context.Context, in *StartRecodingRequest, opts ...grpc.CallOption) (*StartRecodingReply, error) {
	out := new(StartRecodingReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/StartRecoding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) GetStats(ctx context.Context, in *GetRecoderStatsRequest, opts ...grpc.CallOption) (*GetRecoderStatsReply, error) {
	out := new(GetRecoderStatsReply)
	err := c.cc.Invoke(ctx, "/recoder_grpc.Recoder/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoderClient) RecodingEndedChan(ctx context.Context, in *RecodingEndedChanRequest, opts ...grpc.CallOption) (Recoder_RecodingEndedChanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Recoder_serviceDesc.Streams[0], "/recoder_grpc.Recoder/RecodingEndedChan", opts...)
	if err != nil {
		return nil, err
	}
	x := &recoderRecodingEndedChanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recoder_RecodingEndedChanClient interface {
	Recv() (*RecodingEndedChanReply, error)
	grpc.ClientStream
}

type recoderRecodingEndedChanClient struct {
	grpc.ClientStream
}

func (x *recoderRecodingEndedChanClient) Recv() (*RecodingEndedChanReply, error) {
	m := new(RecodingEndedChanReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecoderServer is the server API for Recoder service.
// All implementations must embed UnimplementedRecoderServer
// for forward compatibility
type RecoderServer interface {
	SetLoggingLevel(context.Context, *SetLoggingLevelRequest) (*SetLoggingLevelReply, error)
	NewContext(context.Context, *NewContextRequest) (*NewContextReply, error)
	NewInput(context.Context, *NewInputRequest) (*NewInputReply, error)
	NewOutput(context.Context, *NewOutputRequest) (*NewOutputReply, error)
	CloseContext(context.Context, *CloseContextRequest) (*CloseContextReply, error)
	CloseInput(context.Context, *CloseInputRequest) (*CloseInputReply, error)
	CloseOutput(context.Context, *CloseOutputRequest) (*CloseOutputReply, error)
	StartRecoding(context.Context, *StartRecodingRequest) (*StartRecodingReply, error)
	GetStats(context.Context, *GetRecoderStatsRequest) (*GetRecoderStatsReply, error)
	RecodingEndedChan(*RecodingEndedChanRequest, Recoder_RecodingEndedChanServer) error
	mustEmbedUnimplementedRecoderServer()
}

// UnimplementedRecoderServer must be embedded to have forward compatible implementations.
type UnimplementedRecoderServer struct {
}

func (UnimplementedRecoderServer) SetLoggingLevel(context.Context, *SetLoggingLevelRequest) (*SetLoggingLevelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLoggingLevel not implemented")
}
func (UnimplementedRecoderServer) NewContext(context.Context, *NewContextRequest) (*NewContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContext not implemented")
}
func (UnimplementedRecoderServer) NewInput(context.Context, *NewInputRequest) (*NewInputReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInput not implemented")
}
func (UnimplementedRecoderServer) NewOutput(context.Context, *NewOutputRequest) (*NewOutputReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOutput not implemented")
}
func (UnimplementedRecoderServer) CloseContext(context.Context, *CloseContextRequest) (*CloseContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseContext not implemented")
}
func (UnimplementedRecoderServer) CloseInput(context.Context, *CloseInputRequest) (*CloseInputReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseInput not implemented")
}
func (UnimplementedRecoderServer) CloseOutput(context.Context, *CloseOutputRequest) (*CloseOutputReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseOutput not implemented")
}
func (UnimplementedRecoderServer) StartRecoding(context.Context, *StartRecodingRequest) (*StartRecodingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRecoding not implemented")
}
func (UnimplementedRecoderServer) GetStats(context.Context, *GetRecoderStatsRequest) (*GetRecoderStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRecoderServer) RecodingEndedChan(*RecodingEndedChanRequest, Recoder_RecodingEndedChanServer) error {
	return status.Errorf(codes.Unimplemented, "method RecodingEndedChan not implemented")
}
func (UnimplementedRecoderServer) mustEmbedUnimplementedRecoderServer() {}

// UnsafeRecoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoderServer will
// result in compilation errors.
type UnsafeRecoderServer interface {
	mustEmbedUnimplementedRecoderServer()
}

func RegisterRecoderServer(s *grpc.Server, srv RecoderServer) {
	s.RegisterService(&_Recoder_serviceDesc, srv)
}

func _Recoder_SetLoggingLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoggingLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).SetLoggingLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/SetLoggingLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).SetLoggingLevel(ctx, req.(*SetLoggingLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_NewContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).NewContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/NewContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).NewContext(ctx, req.(*NewContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_NewInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).NewInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/NewInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).NewInput(ctx, req.(*NewInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_NewOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).NewOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/NewOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).NewOutput(ctx, req.(*NewOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_CloseContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).CloseContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/CloseContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).CloseContext(ctx, req.(*CloseContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_CloseInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).CloseInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/CloseInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).CloseInput(ctx, req.(*CloseInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_CloseOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).CloseOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/CloseOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).CloseOutput(ctx, req.(*CloseOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_StartRecoding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecodingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).StartRecoding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/StartRecoding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).StartRecoding(ctx, req.(*StartRecodingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecoderStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoderServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recoder_grpc.Recoder/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoderServer).GetStats(ctx, req.(*GetRecoderStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recoder_RecodingEndedChan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecodingEndedChanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoderServer).RecodingEndedChan(m, &recoderRecodingEndedChanServer{stream})
}

type Recoder_RecodingEndedChanServer interface {
	Send(*RecodingEndedChanReply) error
	grpc.ServerStream
}

type recoderRecodingEndedChanServer struct {
	grpc.ServerStream
}

func (x *recoderRecodingEndedChanServer) Send(m *RecodingEndedChanReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Recoder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recoder_grpc.Recoder",
	HandlerType: (*RecoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLoggingLevel",
			Handler:    _Recoder_SetLoggingLevel_Handler,
		},
		{
			MethodName: "NewContext",
			Handler:    _Recoder_NewContext_Handler,
		},
		{
			MethodName: "NewInput",
			Handler:    _Recoder_NewInput_Handler,
		},
		{
			MethodName: "NewOutput",
			Handler:    _Recoder_NewOutput_Handler,
		},
		{
			MethodName: "CloseContext",
			Handler:    _Recoder_CloseContext_Handler,
		},
		{
			MethodName: "CloseInput",
			Handler:    _Recoder_CloseInput_Handler,
		},
		{
			MethodName: "CloseOutput",
			Handler:    _Recoder_CloseOutput_Handler,
		},
		{
			MethodName: "StartRecoding",
			Handler:    _Recoder_StartRecoding_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Recoder_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecodingEndedChan",
			Handler:       _Recoder_RecodingEndedChan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recoder.proto",
}
